# Generated by Django 3.2 on 2021-07-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(auto_created=True)),
                ('parent', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'child_details',
            },
        ),
        migrations.RemoveField(
            model_name='registrat',
            name='password2',
        ),
    ]
